<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><?php echo $this->title ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 48px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  </head>

  <body>

    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-lg-2"></div>
        <div class="col-xs-12 col-lg-8">
          <?php echo $this->ad_header ?>
        </div>
        <div class="col-xs-12 col-lg-2"></div>
        </div>
      </div>
      
      <div class="row">
        <div class="col-xs-12 col-lg-2"><?php echo $this->ad_left_side ?></div>
        <div class="col-xs-12 col-lg-8">
          <div class="masthead">
            <h3 class="muted"><?php echo $this->site_name ?></h3>
          </div>

          <hr>

          <div class="jumbotron">
            <h1><?php echo $this->main_header ?></h1>
            <p class="lead"><?php echo $this->lead_text ?></p>
          </div>

          <hr>

          <?php echo $this->inner_content; ?>

          <hr>

          <div class="footer">
            <p>&copy; <?php echo $this->company." ".date("Y") ?></p>
          </div>
        </div>
        <div class="col-xs-12 col-lg-2"><?php echo $this->ad_right_side ?></div>
      </div>


    </div> <!-- /container -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>

