          <div class="row-fluid marketing">
            <div  itemscope itemtype="http://schema.org/Article" class="span12">
              <?php foreach($this->posts as $date => $post): ?>    
                <h4><a href="/<?php echo $post->url ?>"><span itemprop="name"><?php echo $post->title ?></span></a></h4>
                <h5><span itemprop="datePublished"><?php echo $date ?></span></h5>
                <h5><span itemprop="author"><?php echo $post->author ?></span></h5>
                <p><?php echo $post->description ?></p>
              <?php endforeach; ?>
            </div>
          </div>
